name: CI

on:
  push:
#  schedule:
#    - cron: '9 * * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate HTML

    steps:
    - name: Setup Pages
      uses: actions/configure-pages@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Checkout this repo
      uses: actions/checkout@v2

    - name: Checkout the ladino-diksionaryo-code
      uses: actions/checkout@v2
      with:
        repository: 'kantoniko/ladino-diksionaryo-code'
        path: ladino-diksionaryo-code

    - name: Checkout the ladino-diksionaryo-data
      uses: actions/checkout@v2
      with:
        repository: 'kantoniko/ladino-diksionaryo-data'
        path: ladino-diksionaryo-data

    - name: Checkout ladino-pages
      uses: actions/checkout@v2
      with:
        repository: 'kantoniko/ladino-pages'
        path: ladino-pages


    - name: Checkout the ladino-diksionaryo-sounds
      uses: actions/checkout@v2
      with:
        repository: 'kantoniko/ladino-diksionaryo-sounds'
        path: ladino-diksionaryo-sounds

    - name: Checkout ladino-los-ladinadores
      uses: actions/checkout@v2
      with:
        repository: 'kantoniko/ladino-los-ladinadores'
        path: ladino-los-ladinadores

    - name: Checkout the ladino-estamos-whatsapeando
      uses: actions/checkout@v2
      with:
        repository: 'kantoniko/ladino-estamos-whatsapeando'
        path: ladino-estamos-whatsapeando

    - name: Checkout the ladino-una-fraza-al-diya
      uses: actions/checkout@v2
      with:
        repository: 'kantoniko/ladino-una-fraza-al-diya'
        path: ladino-una-fraza-al-diya

    - name: Checkout ladino-salu-lulu
      uses: actions/checkout@v2
      with:
        repository: 'kantoniko/ladino-salu-lulu'
        path: ladino-salu-lulu


    - name: Install dependencies
      run: |
          printenv | sort
          python -V
          pip install -r ladino-diksionaryo-code/requirements.txt

    - name: Generate HTML pages
      env:
        PYTHONPATH: ladino-diksionaryo-code
      run: |
          python ladino-diksionaryo-code/ladino/generate.py --dictionary ladino-diksionaryo-data/ --html _site --all --log --whatsapp ladino-estamos-whatsapeando --sounds ladino-diksionaryo-sounds --unafraza ladino-una-fraza-al-diya --pages ladino-pages --books ladino-salu-lulu --ladinadores ladino-los-ladinadores
          echo kantoniko.com > _site/CNAME

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1

    #- name: Commit new files
    #  if: github.repository == 'kantoniko/ladino-diksionaryo-generated'
    #  run: |
    #    GIT_STATUS=$(git status --porcelain docs/)
    #    GIT_COUNT=$(git status --porcelain docs/|wc -l)
    #    echo $GIT_STATUS
    #    echo "count=$GIT_COUNT"
    #    git config --global user.name 'Gabor Szabo'
    #    git config --global user.email 'gabor@szabgab.com'
    #    git add docs/
    #    #if [ "$GIT_STATUS" != "" ] && [ "$GIT_COUNT" != "1" ]; then git commit -m "Automated Web page generation"; fi
    #    #if [ "$GIT_STATUS" != "" ] && [ "$GIT_COUNT" != "1" ]; then git push; fi
    #    #if [ $GIT_COUNT -gt 1 ]; then git commit -m "Automated Web page generation"; fi
    #    #if [ $GIT_COUNT -gt 1 ]; then git push; fi
    #    git commit -m "Automated Web page generation"
    #    git push

    - uses: actions/upload-artifact@v3
      with:
        name: diksionaryo-ladino
        path: ladino-diksionaryo-code/pdf

    - uses: actions/upload-artifact@v3
      with:
        name: hunspell
        path: _site/hunspell


  # Deployment job
  deploy:
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
